[package]
name = "wikopticon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
xml-rs = "0.8"
futures = "0.3.24"
serde = "1.0.144"
mongodb = "2.3.0"
tokio = "1"
